all:
    children:
        site:
            hosts:
                raphaelcorbin@192.168.20.141:
                    
            vars:
                mysql_root_password: Crosemont123
                remote_user: raphaelcorbin
                site_public: public_html
                web_dir: web # répertoire pour un site spécifique. Par exemple, il y a le domaine example.com. Son répertoire racine sera: /home/deploy/public_html/example.com/web. Les répertoires racine sont écrits dans des directives nginx dans le dossier de rôles lors de la création d'un hôte spécifique
                certbot_email: raphaelcorbin@gmail.com
