all:
    children:
        site:
            hosts:
                server:
                    ansible_connection: ssh
                    ansible_user: raphaelcorbin
                    ansible_host: 192.168.20.141
                    ansible_port: 22
            vars:
                mysql_root_password: Crosemont123
                remote_user: raphaelcorbin
                site_public: public_html
                web_dir: web 
                certbot_email: raphaelcorbin@gmail.com
